name: genius
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.5+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  searchable_dropdown: ^1.1.3
  search_widget: ^1.0.2
  shared_preferences: ^2.0.5
  select_form_field: ^2.0.0
  image_picker: ^0.8.4
  flutter_easyloading: ^3.0.0
  date_format: ^2.0.2
  flutter_image_compress: ^1.0.0-nullsafety
  pinch_zoom: ^0.1.0-nullsafety.0
  double_back_to_close_app: ^2.0.1
  skeleton_loader: ^1.0.2+3
  shimmer: ^1.1.2
  datetime_picker_formfield: ^1.0.0
  flutter_local_notifications: ^5.0.0
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.7
  flutter_cupertino_date_picker: ^1.0.26+2
  workmanager: ^0.2.3
  socket_io_client: ^0.9.8
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  awesome_dialog: ^2.1.0
  qrscan: ^0.3.2
  package_info: ^2.0.2
  store_redirect: ^2.0.0
  permission_handler: ^8.1.3
  story_view: ^0.13.1
  dash_chat: ^1.1.16
  firebase_storage: ^10.0.1
  avatar_glow: ^2.0.1
  google_fonts: ^2.1.0
  animated_text_kit: ^4.2.1
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0
  new_version: ^0.2.2
  video_player: ^2.1.12
  chewie: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icon_menu/
    - assets/request/
    - assets/validator/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
